In [2]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')
warnings.simplefilter('ignore')

In [2]:
File = "C:/Users/UserPro/Py_MARCONA/Estimate/1_estimate11_edit.csv"
bk_estimate = pd.read_csv(File, sep=',')

In [3]:
bk_estimate.head()

,ROCK,ZONE,STRAT,IJK,XC,YC,ZC,XINC,YINC,ZINC,...,ZN,FE_IDW,FE_NN,NS,CAT,TD,KVAR,ROCK1,ORE,RCAT
0,5,4,2,0,493070.0,8319490.0,-30,20.0,20.0,12,...,-,-,-,-,-,-,-,800,-,-
1,5,4,2,1,493070.0,8319490.0,-18,20.0,20.0,12,...,-,-,-,-,-,-,-,800,-,-
2,5,4,2,2,493070.0,8319490.0,-6,20.0,20.0,12,...,-,-,-,-,-,-,-,800,-,-
3,5,4,2,3,493070.0,8319490.0,6,20.0,20.0,12,...,-,-,-,-,-,-,-,800,-,-
4,5,4,2,4,493070.0,8319490.0,18,20.0,20.0,12,...,-,-,-,-,-,-,-,800,-,-

In [4]:
bk_estimate= bk_estimate.replace('-', np.nan)

In [5]:
bk_estimate['FE'] = bk_estimate['FE'].astype('float64')
bk_estimate['FE_IDW'] = bk_estimate['FE_IDW'].astype('float64')
bk_estimate['FE_NN'] = bk_estimate['FE_NN'].astype('float64')
bk_estimate['CU'] = bk_estimate['CU'].astype('float64')
bk_estimate['S'] = bk_estimate['S'].astype('float64')
bk_estimate['PB'] = bk_estimate['PB'].astype('float64')
bk_estimate['ZN'] = bk_estimate['ZN'].astype('float64')
bk_estimate['CO'] = bk_estimate['CO'].astype('float64')
bk_estimate['CD'] = bk_estimate['CD'].astype('float64')
bk_estimate['K'] = bk_estimate['K'].astype('float64')
bk_estimate['NA'] = bk_estimate['NA'].astype('float64')
bk_estimate['GA'] = bk_estimate['GA'].astype('float64')
bk_estimate['ROCK'] = bk_estimate['ROCK'].astype('string')
bk_estimate['CAT'] = bk_estimate['CAT'].astype('string')
bk_estimate['RCAT'] = bk_estimate['RCAT'].astype('string')
bk_estimate['ZONE'] = bk_estimate['ZONE'].astype('string')
bk_estimate['STRAT'] = bk_estimate['STRAT'].astype('string')
bk_estimate['ORE'] = bk_estimate['ORE'].astype('string')
bk_estimate['DENSITY']= bk_estimate['DENSITY'].astype('float64')

In [6]:
bk_estimate['MTONN']=bk_estimate['XINC']*bk_estimate['YINC']*bk_estimate['ZINC']*bk_estimate['DENSITY']/1000000
bk_estimate['TONN']=bk_estimate['XINC']*bk_estimate['YINC']*bk_estimate['ZINC']*bk_estimate['DENSITY']

In [7]:
bk_estimate.head()

,ROCK,ZONE,STRAT,IJK,XC,YC,ZC,XINC,YINC,ZINC,...,FE_NN,NS,CAT,TD,KVAR,ROCK1,ORE,RCAT,MTONN,TONN
0,5,4,2,0,493070.0,8319490.0,-30,20.0,20.0,12,...,NaN,NaN,<NA>,NaN,NaN,800,<NA>,<NA>,0.013152,13152.0
1,5,4,2,1,493070.0,8319490.0,-18,20.0,20.0,12,...,NaN,NaN,<NA>,NaN,NaN,800,<NA>,<NA>,0.013152,13152.0
2,5,4,2,2,493070.0,8319490.0,-6,20.0,20.0,12,...,NaN,NaN,<NA>,NaN,NaN,800,<NA>,<NA>,0.013152,13152.0
3,5,4,2,3,493070.0,8319490.0,6,20.0,20.0,12,...,NaN,NaN,<NA>,NaN,NaN,800,<NA>,<NA>,0.013152,13152.0
4,5,4,2,4,493070.0,8319490.0,18,20.0,20.0,12,...,NaN,NaN,<NA>,NaN,NaN,800,<NA>,<NA>,0.013152,13152.0

In [8]:
bk_fe = bk_estimate.dropna(subset=['FE'])

In [9]:
ore_bk_fe = bk_fe.loc[bk_fe['ROCK'].isin(('1','40','1051', '1052', '1053', '2052', '2053'))]

In [10]:
#cutoff_fe20 = ore_bk_fe[ore_bk_fe['FE'] >= 20]
#cutoff_fe30 = ore_bk_fe[ore_bk_fe['FE'] >= 30]
#cutoff_fe50 = ore_bk_fe[ore_bk_fe['FE'] >= 50]

In [11]:
#ore_less_s_2pct = cutoff_fe20[ore_bk['S'] < 2] #1
#ore_between_s_2_3_pct = cutoff_fe20[(ore_bk['S'] >= 2) & (ore_bk['S'] < 3)] #2
#ore_gr_3_2pct = cutoff_fe20[ore_bk['S'] > 3] #

In [12]:
#piv_1 = ore_less_s_2pct[ore_less_s_2pct.CAT=='2'].pivot_table(index=['CAT','ZONE'], values=['MTONN','DENSITY','FE', 'S', 'CU','CO','PB','ZN'], aggfunc={'FE':'mean','S':'mean','CU':'mean','CO':'mean','PB':'mean', 'ZN':'mean','DENSITY':'mean', 'MTONN':'sum'})

#piv_1 = ore_bk_fe[(ore_bk_fe.CAT=='1') | (ore_bk_fe.CAT=='2')].pivot_table(index=['ZONE','STRAT','ORE','CAT'], values=['MTONN','DENSITY','FE', 'S', 'CU','CO','PB','ZN','CD','K','NA','GA'], 
                              #aggfunc={'FE':'mean','S':'mean','CU':'mean','CO':'mean','PB':'mean', 'ZN':'mean','DENSITY':'mean',
                                       #'MTONN':'sum','CD':'mean','K':'mean', 'NA':'mean','GA':'mean'})

In [10]:
piv_1 = ore_bk_fe[(ore_bk_fe.CAT=='1') | (ore_bk_fe.CAT=='2')  & (ore_bk_fe.STRAT!='0')].pivot_table(index=['ZONE','STRAT','ORE'], values=['MTONN','DENSITY','FE', 'S', 'CU','CO','PB','ZN','CD','K','NA','GA'], 
                              aggfunc={'FE':'mean','S':'mean','CU':'mean','CO':'mean','PB':'mean', 'ZN':'mean','DENSITY':'mean',
                                       'MTONN':'sum','CD':'mean','K':'mean', 'NA':'mean','GA':'mean'})

In [11]:
piv_1

                      CD        CO        CU   DENSITY         FE        GA  \
ZONE STRAT ORE
1    1     1    0.000254  0.023752  0.094028  3.646878  37.797551  0.001996
           40   0.000144  0.039282  0.135331  3.640364  37.768794  0.001641
           52   0.000153  0.021366  0.116856  3.314529  26.447825  0.001569
           53   0.000321  0.024422  0.105158  4.132408  49.760893  0.002906
     2     53   0.000050  0.023704  0.098408  3.517684  33.141144  0.002572
2    1     1    0.000199  0.013440  0.104046  3.689572  39.350978  0.000880
           40   0.000159  0.015780  0.104524  3.560154  35.823571  0.001637
           52   0.000191  0.017414  0.110630  3.373320  28.288990  0.000795
           53   0.000540  0.016320  0.122149  4.046888  47.562160  0.001448
     2     1    0.000050  0.010214  0.080013  3.489256  34.269022  0.000250
           40   0.000641  0.006706  0.102077  3.762344  41.641337  0.003695
           53   0.000213  0.017021  0.087779  4.095784  48.724634  0.000427
3    1     1    0.000050  0.009531  0.069530  3.541620  35.391155  0.003241
           40   0.000076  0.011112  0.100213  3.278706  27.055252  0.002450
           52   0.000181  0.012690  0.106282  3.356236  27.683032  0.002304
           53   0.000291  0.035181  0.602155  4.172145  50.714235  0.003153
     2     1    0.000050  0.069766  0.095705  3.923792  45.556737  0.003709
           40   0.000050  0.020726  0.180911  4.057701  48.930834  0.002493
           53   0.000925  0.021070  0.144185  4.155659  50.101912  0.003101
4    1     1    0.000101  0.007375  0.083040  3.628256  37.515745  0.003195
           40   0.000060  0.008074  0.058257  3.464382  33.462631  0.003050
           52   0.000349  0.007201  0.075528  3.447704  30.822116  0.002541
     2     1    0.000289  0.005864  0.201965  3.388317  31.195847  0.003404
           40   0.000072  0.003399  0.029281  3.411853  31.924619  0.002933
           53   0.001007  0.008964  0.089214  4.288310  53.425975  0.004554
5    1     1    0.000122  0.005925  0.051863  3.613523  37.842499  0.003199
           52   0.000503  0.011279  0.082271  3.401115  29.038419  0.002912
     2     1    0.000126  0.005887  0.050814  3.604692  37.590512  0.003167
           53   0.000967  0.006326  0.069613  4.029888  47.252652  0.004382

                       K       MTONN        NA        PB         S        ZN
ZONE STRAT ORE
1    1     1    1.153428   17.875290  1.257861  0.012533  2.104047  0.014532
           40   1.202993    7.752408  1.228322  0.005401  2.301167  0.015322
           52   1.586324  131.557802  1.680065  0.003622  2.166203  0.010082
           53   0.752612   35.856860  0.622281  0.009720  2.732029  0.025777
     2     53   0.775748    0.440112  1.382779  0.000512  1.919499  0.002577
2    1     1    1.312289   11.343715  1.119859  0.014737  1.417123  0.015542
           40   1.014908    4.298668  1.518560  0.010836  2.024723  0.027637
           52   1.502353   64.880790  1.823756  0.014596  1.977562  0.088089
           53   0.509315    7.766256  0.669578  0.022842  3.215626  0.061544
     2     1    0.862510    0.006837  1.278302  0.046248  1.791161  0.095061
           40   0.432494    0.034918  1.119748  0.002732  0.428825  0.009981
           53   0.266092   10.527601  0.132805  0.028976  2.638869  0.066351
3    1     1    1.401543    1.054863  1.792545  0.004828  0.517646  0.018167
           40   1.685761    0.588896  2.206054  0.001797  1.009078  0.007729
           52   1.263738   16.325850  1.860494  0.016358  1.722408  0.036790
           53   0.129638    0.426222  0.158835  0.031786  4.136151  0.069144
     2     1    1.469889    0.454108  1.623370  0.007358  2.803881  0.026972
           40   0.751855    0.699045  2.248614  0.001319  2.349443  0.004817
           53   0.228477   12.645834  0.188762  0.065023  3.275511  0.154344
4    1     1    0.703929    1.212647  1.466766  0.030942  0.527284  0.065870
           40   0.700049    0.559367  1.629616  0.007764  1.039095  0.016969
           52   0.875397   35.429842  1.484960  0.031462  2.064748  0.084935
     2     1    0.612820    0.000602  0.988608  0.126880  0.043677  0.231022
           40   0.523241    0.056379  1.607353  0.004709  0.935973  0.015062
           53   0.100096   89.962971  0.095026  0.068052  3.166493  0.176159
5    1     1    0.637238    0.071318  0.225755  0.008482  0.038464  0.014673
           52   1.424297    4.665251  1.164400  0.079250  1.512675  0.146520
     2     1    0.675991    0.015988  0.231864  0.008952  0.037707  0.015071
           53   0.085290   67.815799  0.089710  0.080346  2.702289  0.195353

In [12]:
piv_2 = ore_bk_fe[(ore_bk_fe.STRAT!='0')].pivot_table(index=['ZONE','STRAT','ORE'], values=['MTONN','DENSITY','FE', 'S', 'CU','CO','PB','ZN','CD','K','NA','GA'], 
                              aggfunc={'FE':'mean','S':'mean','CU':'mean','CO':'mean','PB':'mean', 'ZN':'mean','DENSITY':'mean',
                                       'MTONN':'sum','CD':'mean','K':'mean', 'NA':'mean','GA':'mean'})

In [13]:
piv_2

                      CD        CO        CU   DENSITY         FE        GA  \
ZONE STRAT ORE
1    1     1    0.000265  0.024518  0.097352  3.628987  37.320634  0.001975
           40   0.000155  0.039160  0.134858  3.656002  38.245473  0.001798
           52   0.000150  0.021443  0.134482  3.331339  26.987699  0.001618
           53   0.000310  0.025140  0.102912  4.119854  49.449060  0.002854
     2     53   0.000050  0.021665  0.091219  3.659475  37.273748  0.002545
2    1     1    0.000197  0.013395  0.103575  3.687839  39.306702  0.000883
           40   0.000158  0.015679  0.103880  3.555826  35.698980  0.001637
           52   0.000189  0.017533  0.110647  3.372077  28.252332  0.000801
           53   0.000537  0.016351  0.120789  4.036293  47.288460  0.001439
     2     1    0.000050  0.010214  0.080013  3.489256  34.269022  0.000250
           40   0.000641  0.006706  0.102077  3.762344  41.641337  0.003695
           53   0.000216  0.015557  0.079203  4.055131  47.705522  0.000437
3    1     1    0.000050  0.009573  0.070388  3.493403  33.950914  0.003111
           40   0.000092  0.011693  0.105389  3.273623  26.945294  0.002442
           52   0.000177  0.013070  0.108434  3.364551  27.956921  0.002243
           53   0.000291  0.035148  0.605063  4.172810  50.732001  0.003154
     2     1    0.000050  0.069728  0.096225  3.920912  45.481278  0.003668
           40   0.000050  0.020702  0.181906  4.057449  48.925459  0.002493
           53   0.000837  0.020302  0.130074  4.161527  50.283913  0.002993
4    1     1    0.000101  0.007387  0.083087  3.625713  37.440138  0.003193
           40   0.000060  0.008096  0.058334  3.464251  33.460141  0.003048
           52   0.000344  0.007194  0.075184  3.449950  30.885946  0.002544
     2     1    0.000289  0.005864  0.201965  3.388317  31.195847  0.003404
           40   0.000072  0.003399  0.029281  3.411853  31.924619  0.002933
           53   0.000998  0.008876  0.088222  4.275563  53.128265  0.004514
5    1     1    0.000122  0.005925  0.051863  3.613523  37.842499  0.003199
           52   0.000472  0.010310  0.076478  3.384445  28.511537  0.002900
     2     1    0.000126  0.005887  0.050814  3.604692  37.590512  0.003167
           53   0.000958  0.006224  0.068850  4.024358  47.116369  0.004306

                       K       MTONN        NA        PB         S        ZN
ZONE STRAT ORE
1    1     1    1.169422   19.664634  1.228533  0.012226  2.037435  0.014470
           40   1.184316    8.680912  1.186096  0.006303  2.321306  0.017349
           52   1.598623  201.899429  1.594300  0.003683  2.193518  0.010267
           53   0.761135   40.951895  0.632114  0.009814  2.740513  0.026494
     2     53   0.613060    1.043317  0.750771  0.000550  1.609978  0.002454
2    1     1    1.313091   11.434005  1.125331  0.014553  1.419009  0.015392
           40   1.022314    4.350134  1.541579  0.010656  2.012503  0.027193
           52   1.503405   66.774088  1.818589  0.014403  1.983047  0.085735
           53   0.509439    8.320162  0.669310  0.023461  3.204200  0.061958
     2     1    0.862510    0.006837  1.278302  0.046248  1.791161  0.095061
           40   0.432494    0.034918  1.119748  0.002732  0.428825  0.009981
           53   0.284829   16.887455  0.132917  0.029094  2.458786  0.066915
3    1     1    1.483899    1.381409  1.849869  0.004280  0.542671  0.016670
           40   1.644027    0.663886  2.216621  0.001961  1.047874  0.008350
           52   1.273842   22.084348  1.794868  0.016156  1.873894  0.035472
           53   0.129068    0.429232  0.159261  0.031816  4.121043  0.069220
     2     1    1.521241    0.455378  1.647337  0.007039  2.817383  0.026093
           40   0.751855    0.699752  2.248614  0.001319  2.349958  0.004817
           53   0.269857   27.564093  0.184803  0.068152  3.328549  0.155061
4    1     1    0.706405    1.218120  1.471424  0.030909  0.526054  0.065756
           40   0.702507    0.569240  1.628979  0.007720  1.036058  0.016963
           52   0.882588   41.631214  1.473862  0.031833  2.072296  0.084670
     2     1    0.612820    0.000602  0.988608  0.126880  0.043677  0.231022
           40   0.523241    0.056379  1.607353  0.004709  0.935973  0.015062
           53   0.106132  102.238658  0.099809  0.066591  3.120103  0.174611
5    1     1    0.637238    0.071318  0.225755  0.008482  0.038464  0.014673
           52   1.476013    5.267126  1.202113  0.070555  1.456646  0.132745
     2     1    0.675991    0.015988  0.231864  0.008952  0.037707  0.015071
           53   0.089238   96.718037  0.090106  0.079397  2.707592  0.198885

In [17]:
piv_1.to_csv(File+"aaaaa.csv")

In [ ]:
file=pd.read_csv